Changing to function_hiera_hash
When the nodes are redeployed the hiera is empty always
resulting in the error:

undefined method `delete_if' for nil:NilClass at
/etc/fuel/plugins/opendaylight-0.9/puppet/modules/
opendaylight/manifests/hiera_override.pp:4

Change-Id: Id2f5e5c822f4a67507ceea0db9d776a49c81635e